import functools, numpy
einsum = functools.partial(numpy.einsum, optimize=True)

def ene(cc_obj, amp):
    # Generated by main.py at 2023-10-01 22:55:06
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 0
    # bra_p_order      = 0
    # 
    res  = 1.000000 * einsum('    I,I->',      cc_obj.hpx, amp[1])
    res += 1.000000 * einsum('  ia,ai->',   cc_obj.h1e.ov, amp[0])
    res += 1.000000 * einsum('Iia,Iai->', cc_obj.h1p1e.ov, amp[2])

    # Generated by main.py at 2023-10-01 22:55:10
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 0
    # bra_p_order      = 0
    # 
    res += 1.000000 * einsum('Iia,ai,I->', cc_obj.h1p1e.ov, amp[0], amp[1])
    return res


def res_0(cc_obj, amp):
    # Generated by main.py at 2023-10-01 22:55:27
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res  = 1.000000 * einsum('ai->ai', cc_obj.h1e.vo)

    # Generated by main.py at 2023-10-01 22:55:30
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res +=  1.000000 * einsum('  I,Iai->ai',      cc_obj.hpx, amp[2])
    res += -1.000000 * einsum('  ji,aj->ai',   cc_obj.h1e.oo, amp[0])
    res +=  1.000000 * einsum('  ab,bi->ai',   cc_obj.h1e.vv, amp[0])
    res +=  1.000000 * einsum('  Iai,I->ai', cc_obj.h1p1e.vo, amp[1])
    res += -1.000000 * einsum('Iji,Iaj->ai', cc_obj.h1p1e.oo, amp[2])
    res +=  1.000000 * einsum('Iab,Ibi->ai', cc_obj.h1p1e.vv, amp[2])

    # Generated by main.py at 2023-10-01 22:55:34
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res += -1.000000 * einsum('  jb,bi,aj->ai',   cc_obj.h1e.ov, amp[0], amp[0])
    res += -1.000000 * einsum('  Iji,aj,I->ai', cc_obj.h1p1e.oo, amp[0], amp[1])
    res +=  1.000000 * einsum('  Iab,bi,I->ai', cc_obj.h1p1e.vv, amp[0], amp[1])
    res += -1.000000 * einsum('Ijb,aj,Ibi->ai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('Ijb,bi,Iaj->ai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=  1.000000 * einsum('Ijb,bj,Iai->ai', cc_obj.h1p1e.ov, amp[0], amp[2])

    # Generated by main.py at 2023-10-01 22:55:38
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 3
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res += -1.000000 * einsum('Ijb,bi,aj,I->ai', cc_obj.h1p1e.ov, amp[0], amp[0], amp[1])
    return res


def res_1(cc_obj, amp):
    # Generated by main.py at 2023-10-01 22:55:15
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res  = 1.000000 * einsum('I->I', cc_obj.hpx)

    # Generated by main.py at 2023-10-01 22:55:18
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res += 1.000000 * einsum('  IJ,J->I',      cc_obj.hpp, amp[1])
    res += 1.000000 * einsum('ia,Iai->I',   cc_obj.h1e.ov, amp[2])
    res += 1.000000 * einsum('Iia,ai->I', cc_obj.h1p1e.ov, amp[0])

    # Generated by main.py at 2023-10-01 22:55:22
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res += 1.000000 * einsum('Jia,J,Iai->I', cc_obj.h1p1e.ov, amp[1], amp[2])
    return res


def res_2(cc_obj, amp):
    # Generated by main.py at 2023-10-01 22:55:39
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res  = 1.000000 * einsum('Iai->Iai', cc_obj.h1p1e.vo)

    # Generated by main.py at 2023-10-01 22:55:42
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res += -1.000000 * einsum('ji,Iaj->Iai',   cc_obj.h1e.oo, amp[2])
    res +=  1.000000 * einsum('ab,Ibi->Iai',   cc_obj.h1e.vv, amp[2])
    res +=  1.000000 * einsum('IJ,Jai->Iai',      cc_obj.hpp, amp[2])
    res += -1.000000 * einsum('Iji,aj->Iai', cc_obj.h1p1e.oo, amp[0])
    res +=  1.000000 * einsum('Iab,bi->Iai', cc_obj.h1p1e.vv, amp[0])

    # Generated by main.py at 2023-10-01 22:55:46
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res += -1.000000 * einsum('  jb,aj,Ibi->Iai',   cc_obj.h1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  jb,bi,Iaj->Iai',   cc_obj.h1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Ijb,bi,aj->Iai', cc_obj.h1p1e.ov, amp[0], amp[0])
    res += -1.000000 * einsum('  Jji,J,Iaj->Iai', cc_obj.h1p1e.oo, amp[1], amp[2])
    res +=  1.000000 * einsum('  Jab,J,Ibi->Iai', cc_obj.h1p1e.vv, amp[1], amp[2])
    res += -1.000000 * einsum('Jjb,Iaj,Jbi->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])
    res += -1.000000 * einsum('Jjb,Ibi,Jaj->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])
    res +=  1.000000 * einsum('Jjb,Ibj,Jai->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])

    # Generated by main.py at 2023-10-01 22:55:50
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling030
    # Git Branch:   main
    # Git Commit:   05ec14761826cb755a5d22b81e726e76c2cba1c0
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 3
    # amp_e_order      = 1
    # amp_p_order      = 1
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res += -1.000000 * einsum('Jjb,aj,J,Ibi->Iai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    res += -1.000000 * einsum('Jjb,bi,J,Iaj->Iai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    return res


def exp_nb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:24
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    return res

def exp_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:24
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    return res

def exp_na_ov_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:24
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:24
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    return res

def exp_na_vo_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:24
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    return res

def exp_na_vo_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    return res

def exp_na_oo_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    return res

def exp_na_oo_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    return res

def exp_na_vv_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    return res

def exp_na_vv_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    return res

def exp_nb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    return res

def exp_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    return res

def exp_na_ov_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    return res

def exp_na_vo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    return res

def exp_na_vo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:26
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    return res

def exp_na_oo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:26
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    return res

def exp_na_oo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:26
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    return res

def exp_na_vv_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:26
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    return res

def exp_na_vv_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:27
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    return res

def exp_nb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:28
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    return res

def exp_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:30
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    return res

def exp_na_ov_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:31
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:33
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    return res

def exp_na_vo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:34
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    return res

def exp_na_vo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:37
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    return res

def exp_na_oo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:38
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    return res

def exp_na_oo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:41
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    return res

def exp_na_vv_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:42
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    return res

def exp_na_vv_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:44
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    return res
