import functools, numpy
einsum = functools.partial(numpy.einsum, optimize=True)

def ene(cc_obj, amp):
    # Generated by main.py at 2023-09-30 21:19:41
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling012
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 0
    # 
    res  = 1.000000 * einsum('    I,I->',      cc_obj.hpx, amp[1])
    res += 1.000000 * einsum('  ia,ai->',   cc_obj.h1e.ov, amp[0])
    res += 1.000000 * einsum('Iia,Iai->', cc_obj.h1p1e.ov, amp[2])

    # Generated by main.py at 2023-09-30 21:19:42
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling011
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 0
    # 
    res += 1.000000 * einsum('Iia,ai,I->', cc_obj.h1p1e.ov, amp[0], amp[1])
    return res


def res_0(cc_obj, amp):
    # Generated by main.py at 2023-10-01 21:48:13
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling025
    # Git Branch:   main
    # Git Commit:   3bc31685b43f90bb621c4c4d7dbb161b97523e4c
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res  = 1.000000 * einsum('ai->ai', cc_obj.h1e.vo)

    # Generated by main.py at 2023-10-01 21:48:14
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling025
    # Git Branch:   main
    # Git Commit:   3bc31685b43f90bb621c4c4d7dbb161b97523e4c
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res +=  1.000000 * einsum('  I,Iai->ai',      cc_obj.hpx, amp[2])
    res += -1.000000 * einsum('  ji,aj->ai',   cc_obj.h1e.oo, amp[0])
    res +=  1.000000 * einsum('  ab,bi->ai',   cc_obj.h1e.vv, amp[0])
    res +=  1.000000 * einsum('  Iai,I->ai', cc_obj.h1p1e.vo, amp[1])
    res += -1.000000 * einsum('Iji,Iaj->ai', cc_obj.h1p1e.oo, amp[2])
    res +=  1.000000 * einsum('Iab,Ibi->ai', cc_obj.h1p1e.vv, amp[2])

    # Generated by main.py at 2023-10-01 21:48:17
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling025
    # Git Branch:   main
    # Git Commit:   3bc31685b43f90bb621c4c4d7dbb161b97523e4c
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res += -1.000000 * einsum('  jb,bi,aj->ai',   cc_obj.h1e.ov, amp[0], amp[0])
    res += -1.000000 * einsum('  Iji,aj,I->ai', cc_obj.h1p1e.oo, amp[0], amp[1])
    res +=  1.000000 * einsum('  Iab,bi,I->ai', cc_obj.h1p1e.vv, amp[0], amp[1])
    res += -1.000000 * einsum('Ijb,aj,Ibi->ai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('Ijb,bi,Iaj->ai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=  1.000000 * einsum('Ijb,bj,Iai->ai', cc_obj.h1p1e.ov, amp[0], amp[2])

    # Generated by main.py at 2023-10-01 21:48:28
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling025
    # Git Branch:   main
    # Git Commit:   3bc31685b43f90bb621c4c4d7dbb161b97523e4c
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: a+_o a_v
    # 
    # commu_hbar_order = 3
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 0
    # 
    res += -1.000000 * einsum('Ijb,bi,aj,I->ai', cc_obj.h1p1e.ov, amp[0], amp[0], amp[1])
    return res


def res_1(cc_obj, amp):
    # Generated by main.py at 2023-09-30 21:19:41
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling001
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res  = 1.000000 * einsum('I->I', cc_obj.hpx)

    # Generated by main.py at 2023-09-30 21:19:43
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling014
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res += 1.000000 * einsum('    J,IJ->I',      cc_obj.hpx, amp[3])
    res += 1.000000 * einsum('    IJ,J->I',      cc_obj.hpp, amp[1])
    res += 1.000000 * einsum('  ia,Iai->I',   cc_obj.h1e.ov, amp[2])
    res += 1.000000 * einsum('  Iia,ai->I', cc_obj.h1p1e.ov, amp[0])
    res += 1.000000 * einsum('Jia,IJai->I', cc_obj.h1p1e.ov, amp[4])

    # Generated by main.py at 2023-09-30 21:19:43
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling012
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 1
    # 
    res += 1.000000 * einsum('Jia,J,Iai->I', cc_obj.h1p1e.ov, amp[1], amp[2])
    res += 1.000000 * einsum('Jia,ai,IJ->I', cc_obj.h1p1e.ov, amp[0], amp[3])
    return res


def res_2(cc_obj, amp):
    # Generated by main.py at 2023-09-30 21:19:53
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling014
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 0
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res  = 1.000000 * einsum('Iai->Iai', cc_obj.h1p1e.vo)

    # Generated by main.py at 2023-09-30 21:19:53
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling011
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res +=  1.000000 * einsum('  J,IJai->Iai',      cc_obj.hpx, amp[4])
    res += -1.000000 * einsum('  ji,Iaj->Iai',   cc_obj.h1e.oo, amp[2])
    res +=  1.000000 * einsum('  ab,Ibi->Iai',   cc_obj.h1e.vv, amp[2])
    res +=  1.000000 * einsum('  IJ,Jai->Iai',      cc_obj.hpp, amp[2])
    res += -1.000000 * einsum('  Iji,aj->Iai', cc_obj.h1p1e.oo, amp[0])
    res +=  1.000000 * einsum('  Iab,bi->Iai', cc_obj.h1p1e.vv, amp[0])
    res +=  1.000000 * einsum('  Jai,IJ->Iai', cc_obj.h1p1e.vo, amp[3])
    res += -1.000000 * einsum('Jji,IJaj->Iai', cc_obj.h1p1e.oo, amp[4])
    res +=  1.000000 * einsum('Jab,IJbi->Iai', cc_obj.h1p1e.vv, amp[4])

    # Generated by main.py at 2023-09-30 21:19:54
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling001
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res += -1.000000 * einsum('  jb,aj,Ibi->Iai',   cc_obj.h1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  jb,bi,Iaj->Iai',   cc_obj.h1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Ijb,bi,aj->Iai', cc_obj.h1p1e.ov, amp[0], amp[0])
    res += -1.000000 * einsum('  Jji,J,Iaj->Iai', cc_obj.h1p1e.oo, amp[1], amp[2])
    res += -1.000000 * einsum('  Jji,aj,IJ->Iai', cc_obj.h1p1e.oo, amp[0], amp[3])
    res +=  1.000000 * einsum('  Jab,J,Ibi->Iai', cc_obj.h1p1e.vv, amp[1], amp[2])
    res +=  1.000000 * einsum('  Jab,bi,IJ->Iai', cc_obj.h1p1e.vv, amp[0], amp[3])
    res += -1.000000 * einsum('Jjb,aj,IJbi->Iai', cc_obj.h1p1e.ov, amp[0], amp[4])
    res += -1.000000 * einsum('Jjb,bi,IJaj->Iai', cc_obj.h1p1e.ov, amp[0], amp[4])
    res +=  1.000000 * einsum('Jjb,bj,IJai->Iai', cc_obj.h1p1e.ov, amp[0], amp[4])
    res += -1.000000 * einsum('Jjb,Iaj,Jbi->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])
    res += -1.000000 * einsum('Jjb,Ibi,Jaj->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])
    res +=  1.000000 * einsum('Jjb,Ibj,Jai->Iai', cc_obj.h1p1e.ov, amp[2], amp[2])

    # Generated by main.py at 2023-09-30 21:20:05
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling014
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b a+_o a_v
    # 
    # commu_hbar_order = 3
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 1
    # 
    res += -1.000000 * einsum('Jjb,aj,J,Ibi->Iai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    res += -1.000000 * einsum('Jjb,bi,J,Iaj->Iai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    res += -1.000000 * einsum('Jjb,bi,aj,IJ->Iai', cc_obj.h1p1e.ov, amp[0], amp[0], amp[3])
    return res


def res_3(cc_obj, amp):
    # Generated by main.py at 2023-09-30 21:19:44
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling011
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b b
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 2
    # 
    res  = 1.000000 * einsum('  IK,JK->IJ',      cc_obj.hpp, amp[3])
    res += 1.000000 * einsum('  JK,IK->IJ',      cc_obj.hpp, amp[3])
    res += 1.000000 * einsum('ia,IJai->IJ',   cc_obj.h1e.ov, amp[4])
    res += 1.000000 * einsum('Iia,Jai->IJ', cc_obj.h1p1e.ov, amp[2])
    res += 1.000000 * einsum('Jia,Iai->IJ', cc_obj.h1p1e.ov, amp[2])

    # Generated by main.py at 2023-09-30 21:19:48
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling014
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b b
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 0
    # bra_p_order      = 2
    # 
    res += 1.000000 * einsum('Kia,K,IJai->IJ', cc_obj.h1p1e.ov, amp[1], amp[4])
    res += 1.000000 * einsum('Kia,Iai,JK->IJ', cc_obj.h1p1e.ov, amp[2], amp[3])
    res += 1.000000 * einsum('Kia,Jai,IK->IJ', cc_obj.h1p1e.ov, amp[2], amp[3])
    return res

def res_4(cc_obj, amp):
    # Generated by main.py at 2023-09-30 21:19:56
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling001
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b b a+_o a_v
    # 
    # commu_hbar_order = 1
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 2
    # 
    res  = -1.000000 * einsum('ji,IJaj->IJai',   cc_obj.h1e.oo, amp[4])
    res +=  1.000000 * einsum('ab,IJbi->IJai',   cc_obj.h1e.vv, amp[4])
    res +=  1.000000 * einsum('IK,JKai->IJai',      cc_obj.hpp, amp[4])
    res +=  1.000000 * einsum('JK,IKai->IJai',      cc_obj.hpp, amp[4])
    res += -1.000000 * einsum('Iji,Jaj->IJai', cc_obj.h1p1e.oo, amp[2])
    res +=  1.000000 * einsum('Iab,Jbi->IJai', cc_obj.h1p1e.vv, amp[2])
    res += -1.000000 * einsum('Jji,Iaj->IJai', cc_obj.h1p1e.oo, amp[2])
    res +=  1.000000 * einsum('Jab,Ibi->IJai', cc_obj.h1p1e.vv, amp[2])

    # Generated by main.py at 2023-09-30 21:20:01
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling012
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b b a+_o a_v
    # 
    # commu_hbar_order = 2
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 2
    # 
    res += -1.000000 * einsum('  jb,aj,IJbi->IJai',   cc_obj.h1e.ov, amp[0], amp[4])
    res += -1.000000 * einsum('  jb,bi,IJaj->IJai',   cc_obj.h1e.ov, amp[0], amp[4])
    res += -1.000000 * einsum('  jb,Iaj,Jbi->IJai',   cc_obj.h1e.ov, amp[2], amp[2])
    res += -1.000000 * einsum('  jb,Ibi,Jaj->IJai',   cc_obj.h1e.ov, amp[2], amp[2])
    res += -1.000000 * einsum('  Ijb,aj,Jbi->IJai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Ijb,bi,Jaj->IJai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Jjb,aj,Ibi->IJai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Jjb,bi,Iaj->IJai', cc_obj.h1p1e.ov, amp[0], amp[2])
    res += -1.000000 * einsum('  Kji,K,IJaj->IJai', cc_obj.h1p1e.oo, amp[1], amp[4])
    res += -1.000000 * einsum('  Kji,Iaj,JK->IJai', cc_obj.h1p1e.oo, amp[2], amp[3])
    res += -1.000000 * einsum('  Kji,Jaj,IK->IJai', cc_obj.h1p1e.oo, amp[2], amp[3])
    res +=  1.000000 * einsum('  Kab,K,IJbi->IJai', cc_obj.h1p1e.vv, amp[1], amp[4])
    res +=  1.000000 * einsum('  Kab,Ibi,JK->IJai', cc_obj.h1p1e.vv, amp[2], amp[3])
    res +=  1.000000 * einsum('  Kab,Jbi,IK->IJai', cc_obj.h1p1e.vv, amp[2], amp[3])
    res += -1.000000 * einsum('Kjb,Iaj,JKbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res += -1.000000 * einsum('Kjb,Ibi,JKaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=  1.000000 * einsum('Kjb,Ibj,JKai->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res += -1.000000 * einsum('Kjb,Jaj,IKbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res += -1.000000 * einsum('Kjb,Jbi,IKaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=  1.000000 * einsum('Kjb,Jbj,IKai->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=  1.000000 * einsum('Kjb,Kai,IJbj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res += -1.000000 * einsum('Kjb,Kaj,IJbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res += -1.000000 * einsum('Kjb,Kbi,IJaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])

    # Generated by main.py at 2023-09-30 21:20:16
    # Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    # Hostname:     pauling011
    # Git Branch:   main
    # Git Commit:   3be3187c4fc03d1909a9be6b258176358e3b4172
    # 
    # amp[0]: a+_v a_o
    # amp[1]: b+
    # amp[2]: b+ a+_v a_o
    # amp[3]: b+ b+
    # amp[4]: b+ b+ a+_v a_o
    # res: b b a+_o a_v
    # 
    # commu_hbar_order = 3
    # amp_e_order      = 1
    # amp_p_order      = 2
    # bra_e_order      = 1
    # bra_p_order      = 2
    # 
    res += -1.000000 * einsum('Kjb,K,Iaj,Jbi->IJai', cc_obj.h1p1e.ov, amp[1], amp[2], amp[2])
    res += -1.000000 * einsum('Kjb,K,Ibi,Jaj->IJai', cc_obj.h1p1e.ov, amp[1], amp[2], amp[2])
    res += -1.000000 * einsum('Kjb,aj,K,IJbi->IJai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[4])
    res += -1.000000 * einsum('Kjb,aj,Ibi,JK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res += -1.000000 * einsum('Kjb,aj,Jbi,IK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res += -1.000000 * einsum('Kjb,bi,K,IJaj->IJai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[4])
    res += -1.000000 * einsum('Kjb,bi,Iaj,JK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res += -1.000000 * einsum('Kjb,bi,Jaj,IK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    return res


def exp_nb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:24
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    return res

def exp_na_vo(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:25
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_vo_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:26
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    return res

def exp_na_ov(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:27
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    return res

def exp_na_ov_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:31
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj,IJ->bjJ' , lam[2], amp[0], amp[0], amp[3])
    res +=    -1.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], amp[1], amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,aj,Ibi,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,bi,Iaj,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    return res

def exp_na_oo(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:31
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    return res

def exp_na_oo_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:34
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    return res

def exp_na_vv(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:34
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    return res

def exp_na_vv_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:10:36
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    return res

def exp_nb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:44
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    return res

def exp_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('I,IJ->J'           , lam[1], amp[3])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,IJai->J'       , lam[2], amp[4])
    return res

def exp_na_ov_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    return res

def exp_na_vo_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    return res

def exp_na_vo_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    return res

def exp_na_oo_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:46
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    return res

def exp_na_oo_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:46
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    return res

def exp_na_vv_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:46
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    return res

def exp_na_vv_xb_3(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:46
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    return res

def exp_nb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:47
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    return res

def exp_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:50
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('I,IJ->J'           , lam[1], amp[3])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,IJai->J'       , lam[2], amp[4])
    return res

def exp_na_ov_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:51
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:54
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    return res

def exp_na_vo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:55
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    return res

def exp_na_vo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:03
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj,IJ->bjJ' , lam[2], amp[0], amp[0], amp[3])
    res +=    -1.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], amp[1], amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,aj,Ibi,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,bi,Iaj,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    return res

def exp_na_oo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:04
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    return res

def exp_na_oo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:08
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    return res

def exp_na_vv_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:09
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    return res

def exp_na_vv_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:12
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    return res

def exp_nb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:28:34
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    return res

def exp_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:29:16
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('I,IJ->J'           , lam[1], amp[3])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,IJai->J'       , lam[2], amp[4])
    return res

def exp_na_ov_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:29:37
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:30:28
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    return res

def exp_na_vo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:30:50
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    return res

def exp_na_vo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:31:50
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj,IJ->bjJ' , lam[2], amp[0], amp[0], amp[3])
    res +=    -1.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], amp[1], amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,aj,Ibi,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,bi,Iaj,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    return res

def exp_na_oo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:32:13
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    return res

def exp_na_oo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:33:03
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    return res

def exp_na_vv_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:33:26
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    return res

def exp_na_vv_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:34:14
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   a256f996f2fbfa91ac721f723c393e84c7325eea

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    return res
